spring:
  application:
    name: springbootaireviewdemo
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  health:
    livenessState:
      enabled: true
  endpoint:
    health:
      group:
        liveness:
          include: livenessState
